Net640/apps/chat/urls.py
from django.urls import re_path, path
from Net640.apps.chat import views


app_name = 'chat'
urlpatterns = [
    # path for entering chat room with person
    re_path(r'^id(?P<user_id>([\d]*))/$', views.chat_room, name="chat_room"),
    # path for processing POST messages from user chat_room(basicaly sended by js as async request)
    path(r'action/', views.user_message_action, name="user_message_action"),
]

Net640/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from Net640.settings import MEDIA_ROOT, MEDIA_URL, STATIC_URL, STATIC_ROOT
from django.conf.urls.static import static

import Net640.apps.images.views as image_views

try:
    from Net640.local_settings import DEBUG
except ImportError:
    from Net640.settings import DEBUG

media_url = [
    # next function is working in cooperation with nginx:
    #  - nginx recieve request for some resource in /media/*
    #  - ngnix moves this request to views.get_image
    #  - get_image checks permissions and return resource or return 404
    re_path(r'^media/users/(?P<username>(\w*))/(?P<imagename>(.*))', image_views.get_image, name="get_image"),
]


# for sentry debug
def trigger_error(request):
    1 / 0


urlpatterns = [
    path('', include('Net640.apps.user_posts.urls', namespace='posts')),
    path('user/', include('Net640.apps.user_profile.urls', namespace='profile')),
    path('friends/', include('Net640.apps.friends.urls', namespace='friends')),
    path('chat/', include('Net640.apps.chat.urls', namespace='chat')),
    path('images/', include('Net640.apps.images.urls', namespace='images')),
    path('admin/', admin.site.urls),
    path('sentry-debug/', trigger_error),
] + media_url

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

Net640/apps/chat/models.py
import asyncio

from channels.layers import get_channel_layer

from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone

from Net640.apps.user_profile.models import User
from Net640.errors import ERR_EXCEED_LIMIT
from Net640.settings import MAX_PAGE_SIZE
from Net640.apps.updateflow.helpers import get_updateflow_room_name


CHANNEL_LAYER = get_channel_layer()


class Message(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(User, related_name='message_author', on_delete=models.CASCADE)
    chat_room = models.TextField()
    content = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)

    class Meta:
        app_label = 'chat'

    def save(self, *args, **kwargs):
        # Calculate message size
        # use latest id as reference
        try:
            message_size = len(str(Message.objects.latest('id').id))
        except ObjectDoesNotExist:
            message_size = 1
        message_size += len(self.content)
        message_size += len(str(self.author_id))
        message_size += len(str(self.timestamp))
        message_size += len(str(self.author_id))
        message_size += len(str(self.chat_room))

        response = {'upd_user_page_size': message_size, 'error': False}

        if self.author.get_size() + message_size * 8 > MAX_PAGE_SIZE:
            response.update({'error': True, 'error_reason': 'not enough free space'})

        room_name = get_updateflow_room_name(self.author_id)
        update_coro = CHANNEL_LAYER.group_send(room_name, {
            'type': 'update_flow',
            'message': response
        })
        event_loop = asyncio.get_event_loop()
        asyncio.ensure_future(update_coro, loop=event_loop)
        # raise error to prevent Message to save
        if response['error']:
            raise Exception(ERR_EXCEED_LIMIT)

        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        message_size = 0
        try:
            message_size += len(str(self.id))
            message_size += len(self.content)
            message_size += len(str(self.author_id))
            message_size += len(str(self.timestamp))
            message_size += len(str(self.author_id))
            message_size += len(str(self.chat_room))
            if message_size:
                # send decrement info
                self.author.msg_upd_page_size(-message_size)
        finally:
            super().delete(*args, **kwargs)

    def __str__(self):
        return '[{timestamp}] {author}: {content}'.format(**self.as_dict())

    @property
    def formatted_timestamp(self):
        return self.timestamp.strftime('%b %-d %-I:%M %p')

    def as_dict(self):
        return {'author': self.author.username, 'content': self.content, 'timestamp': self.formatted_timestamp}

Net640/apps/chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.views.decorators.http import require_POST, require_GET

from Net640.apps.chat.models import Message

User = get_user_model()


@login_required
@require_GET
def chat_room(request, user_id):
    """
    Prepare variables for creating chat room.
    Render chat room from template.
    """
    # Group name for chat. It's uniq.
    user_to_chat = get_object_or_404(User, pk=user_id)
    id_list = [request.user.pk, int(user_id)]
    id_list.sort()
    room_name = "room_" + str(id_list[0]) + "_with_" + str(id_list[1])

    # show messages stored id DB to user
    messages = Message.objects.filter(chat_room=room_name)

    return render(request, 'chat/room.html', {
        'room_name': room_name,
        'user_to_chat': user_to_chat,
        'user': request.user,
        'messages': messages
    })


@login_required
@require_POST
def user_message_action(request):
    """
    Process any action on user messages.
    For example - remove message.
    """
    context = {}
    user = request.user
    message_id = request.POST.get('message_id', None)
    message = get_object_or_404(Message, id=message_id)
    action = request.POST.get('action', None)

    if action == 'remove':
        if user == message.author:
            message.delete()
            context.update({"result": True})
    return JsonResponse(context)

Net640/apps/chat/templates/chat/room.html
{% extends "base.html" %}

{% block title %}User:  {{user.username}}{% endblock %}
{% load static %}
{% block css_rules %}
<link rel='stylesheet' href='{% static 'chat/css/chat.css' %}' />
<link rel='stylesheet' href="{% static 'vendor/css/fontawesome/all.css' %}" />
{% endblock %}

{% block content %}
<!-- default values -->
<div id="default_values" class="d-none"
     data-room_name="{{room_name}}"
     data-master_name="{{user.username}}"
     data-action-url="{% url 'chat:user_message_action' %}"
     >
</div>
<!-- end of default values -->


<div class="container">

  <div class="row mt-2">
    <div class="col-12 mx-auto">You are talking with: <b>{{user_to_chat}}</b></div>
  </div>


  <div class="row chat_window" id="chat_window"> 
    <div class="col-12 col-md-8 mx-auto">
      <table class="table" id="chat_table">
        <tbody id="chat_table_body">
          {% for message in messages %}
            <tr class="chat__table_message">
              <td class="chat__table_message_time">{{ message.formatted_timestamp }}</td>
              {% ifequal user.id message.author.id %}
                <td class="chat__table_message_content chat__table_message_written_by_owner" > {{ message.content }} </td>
                <td><i class="far fa-trash-alt" data-action='remove' data-action-url="{% url 'chat:user_message_action' %}" data-message-id="{{ message.id }}"></i></td>
              {% else %}
                <td class="chat__table_message_content" >{{ message.content }}</td>
              {% endifequal %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-12 mx-auto">
      <form class="mx-auto" method="post" id="send_message_form">
        {% csrf_token %}
        <textarea name="content" class="w-75" id="send_message_form_text"></textarea>
        <div class="btn btn-secondary w-75" id="send_message_btn">Send Message</div>
      </form>
    </div>
  </div>

</div>

{% endblock %}

{% block scripts %}
<script type="text/javascript" src='{% static "js/basic_func.js" %}'></script>
<script type="text/javascript" src='{% static "chat/js/chat.js" %}'></script>
{% endblock %}