Net640/apps/user_profile/urls.py
from django.urls import path, re_path
from Net640.apps.user_profile import views, classy_views

app_name = 'profile'
urlpatterns = [
    path(r'signup/', views.signup_view, name="signup"),
    path(r'login/', views.login_view, name="login"),
    path(r'my_profile/', views.profile_view, name="my_profile"),
    path(r'logout/', views.logout_view, name="logout"),
    path(r'account_activation_sent/', views.signup_confirm_sent, name='account_activation_sent'),
    re_path(r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.signup_confirm, name='signup_confirm'),
    path(r'reset_password/', classy_views.Net640PasswordResetView.as_view(), name="reset_password"),
    path(r'reset/done/', classy_views.Net640PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(r'reset/complete/', classy_views.Net640PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    re_path(r'reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            classy_views.Net640PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

Net640/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from Net640.settings import MEDIA_ROOT, MEDIA_URL, STATIC_URL, STATIC_ROOT
from django.conf.urls.static import static

import Net640.apps.images.views as image_views

try:
    from Net640.local_settings import DEBUG
except ImportError:
    from Net640.settings import DEBUG

media_url = [
    # next function is working in cooperation with nginx:
    #  - nginx recieve request for some resource in /media/*
    #  - ngnix moves this request to views.get_image
    #  - get_image checks permissions and return resource or return 404
    re_path(r'^media/users/(?P<username>(\w*))/(?P<imagename>(.*))', image_views.get_image, name="get_image"),
]


# for sentry debug
def trigger_error(request):
    1 / 0


urlpatterns = [
    path('', include('Net640.apps.user_posts.urls', namespace='posts')),
    path('user/', include('Net640.apps.user_profile.urls', namespace='profile')),
    path('friends/', include('Net640.apps.friends.urls', namespace='friends')),
    path('chat/', include('Net640.apps.chat.urls', namespace='chat')),
    path('images/', include('Net640.apps.images.urls', namespace='images')),
    path('admin/', admin.site.urls),
    path('sentry-debug/', trigger_error),
] + media_url

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

Net640/apps/user_profile/forms.py
from django import forms
from django.contrib.auth.hashers import make_password
from django.contrib.auth.forms import PasswordResetForm
from django.core.validators import RegexValidator
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext_lazy as _

from Net640.apps.user_profile.models import User
from Net640.settings import MAX_PAGE_SIZE, DATE_FORMAT
from Net640.errors import ERR_EXCEED_LIMIT


username_validator = RegexValidator(r'^[\w\d_\-]+$',
                                    "Username should contain only letters, digits, underscores, and dashes")


class CleanPasswordMixin:

    def _clean_password(self, cleaned_data):
        password = cleaned_data['password']
        password_again = cleaned_data['password_again']
        validation_errors = list()

        if len(password) == 0 and len(password_again) == 0:
            return cleaned_data, validation_errors
        if password != password_again:
            validation_errors.append(forms.ValidationError("Passwords mismatch"))
        elif len(password) < 8:
            validation_errors.append(forms.ValidationError("Password length must be at least 8 symbols"))
        return cleaned_data, validation_errors


class UserForm(CleanPasswordMixin, forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput, max_length=120, min_length=3, validators=[username_validator])
    email = forms.EmailField(widget=forms.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput)
    password_again = forms.CharField(widget=forms.PasswordInput)
    avatar = forms.ImageField(widget=forms.FileInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password_again', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['avatar'].required = False
        self.fields['avatar'].label = 'Upload Avatar:'
        self.fields['avatar'].widget.attrs.update({
            'class': 'form-control-file'
        })

        if self.fields.get('username', None):
            self.fields['username'].widget.attrs.update({
                'placeholder': 'Username', 'class': 'form-control mb-3'
            })
            self.fields['username'].help_text = ''
            self.fields['username'].label = ''

        self.fields['email'].widget.attrs.update({
            'placeholder': 'Email', 'class': 'form-control mb-3'
        })
        self.fields['email'].help_text = ''
        self.fields['email'].label = ''

        self.fields['password'].widget.attrs.update({
            'placeholder': 'Password', 'class': 'form-control mb-3'
        })
        self.fields['password'].help_text = ''
        self.fields['password'].label = ''

        self.fields['password_again'].widget.attrs.update({
            'placeholder': 'Repeat password', 'class': 'form-control mb-3'
        })
        self.fields['password_again'].help_text = ''
        self.fields['password_again'].label = ''

        # this code is for descendants
        # remove unnecessary fields
        unnecessary = set(self.fields.keys()) - set(self.Meta.fields)
        for field in unnecessary:
            self.fields.pop(field)

    def clean(self):
        cleaned_data = super().clean()
        validation_errors = list()

        # Calculate form size
        # use latest id as reference
        try:
            form_size = len(str(User.objects.latest('id').id))
        except ObjectDoesNotExist:
            form_size = 1
        # if we already had errors, than we will skip this fields
        for field_name in set(self.changed_data) - set(self.errors):
            if field_name in ['password_again']:
                continue
            if field_name == 'avatar':
                form_size += cleaned_data['avatar'].size
                continue
            form_size += len(str(cleaned_data[field_name]))
        if form_size > MAX_PAGE_SIZE:
            validation_errors.append(forms.ValidationError(_('You have only 640Kb for all purposes!'), code='oversize'))

        # Clean password
        cleaned_data, password_clean_errors = self._clean_password(cleaned_data)

        validation_errors += password_clean_errors
        if validation_errors:
            raise forms.ValidationError(validation_errors)

        new_pass = cleaned_data['password']
        if len(new_pass) > 0:
            cleaned_data['password'] = make_password(new_pass)

        return cleaned_data


class UserUpdateForm(UserForm):
    firstname = forms.CharField(widget=forms.TextInput)
    lastname = forms.CharField(widget=forms.TextInput)
    patronymic = forms.CharField(widget=forms.TextInput)
    birth_date = forms.DateField(widget=forms.DateInput, input_formats=[DATE_FORMAT])

    class Meta(UserForm.Meta):
        fields = ('firstname', 'lastname', 'patronymic', 'birth_date', 'password', 'password_again', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = False

        self.fields['firstname'].widget.attrs.update({
            'placeholder': 'First Name', 'class': 'form-control mb-3'
        })
        self.fields['firstname'].help_text = ''
        self.fields['firstname'].label = ''

        self.fields['lastname'].widget.attrs.update({
            'placeholder': 'Last Name', 'class': 'form-control mb-3'
        })
        self.fields['lastname'].help_text = ''
        self.fields['lastname'].label = ''

        self.fields['patronymic'].widget.attrs.update({
            'placeholder': 'Patronymic', 'class': 'form-control mb-3'
        })
        self.fields['patronymic'].help_text = ''
        self.fields['patronymic'].label = ''

        self.fields['birth_date'].widget.attrs.update({
            'placeholder': 'Birth Date', 'class': 'form-control mb-3'
        })
        self.fields['birth_date'].widget.format = DATE_FORMAT
        self.fields['birth_date'].help_text = ''
        self.fields['birth_date'].label = ''

        self.fields['password'].widget.attrs.update({
            'placeholder': 'New password'})
        self.fields['password_again'].widget.attrs.update({
            'placeholder': 'Repeat new password'})

    def clean(self):
        cleaned_data = super().clean()
        delta = 0
        # if we have empty password field then skip updating this field
        if 'password' in self.changed_data:
            password = cleaned_data['password']
            if len(password) == 0:
                index = self.changed_data.index('password')
                self.changed_data.pop(index)
                cleaned_data.pop('password')
        # get approximate size of user fields
        original_sizes = self.instance.get_fields_size()
        # check delta for all fields except password_again (not exist in DB)
        for field_name in self.changed_data:
            if field_name in ['password_again']:
                continue
            updated_value = cleaned_data[field_name]
            if not updated_value:
                updated_len = 0
            elif field_name == 'avatar':
                updated_len = updated_value.size
            else:
                updated_len = len(str(updated_value))

            original_len = original_sizes[field_name]
            delta += updated_len - original_len

        if self.instance.get_size() + delta > MAX_PAGE_SIZE:
            raise forms.ValidationError(_(ERR_EXCEED_LIMIT), code='oversize')

        return cleaned_data


class UserRequestPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput, max_length=256)

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({
            'placeholder': 'Email', 'class': 'form-control mb-3'
        })
        self.fields['email'].help_text = ''
        self.fields['email'].label = ''


class UserPasswordUpdateForm(UserForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_again = forms.CharField(widget=forms.PasswordInput)

    class Meta(UserForm.Meta):
        fields = ('password', 'password_again')


class UserPasswordResetConfirmForm(CleanPasswordMixin, forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    password_again = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        cleaned_data, password_clean_errors = self._clean_password(cleaned_data)

        if password_clean_errors:
            raise forms.ValidationError(password_clean_errors)

        return cleaned_data

    def save(self, commit=True):
        password = self.cleaned_data["password"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user

Net640/apps/user_profile/views.py
import logging
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_http_methods, require_GET
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string

from Net640.httpcodes import HTTP_BAD_REQUEST, HTTP_OK, HTTP_UNAUTHORIZED, HTTP_SERVICE_UNAVAILABLE
from Net640.apps.user_profile.helpers import base, save_user_by_form, update_user_by_form
from Net640.apps.user_profile.forms import UserForm, UserUpdateForm

from Net640.apps.user_profile.models import DEFAULT_AVATAR_URL
from Net640.apps.user_profile.tokens import account_activation_token


logger = logging.getLogger('user_profile')

User = get_user_model()


@require_http_methods(["GET", "POST"])
def login_view(request):
    context = base(request)
    context.update({'login_failed': False})
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('posts:mainpage')
        else:
            context.update({'login_failed': True})
            return render(request, 'login.html', context, status=HTTP_UNAUTHORIZED)
    else:
        return render(request, "login.html", context)


@require_http_methods(["GET", "POST"])
def signup_view(request):
    context = base(request)
    status = HTTP_OK
    if request.method == "POST":
        signup_form, valid = save_user_by_form(request, context)
        context.update({'signup_form': signup_form})
        if valid:
            user = context['user']
            # send activation code
            subject = 'Activate Your Net640kb Account'
            current_site = get_current_site(request)
            message = render_to_string('profile_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            try:
                user.email_user(subject, message)
            except Exception as error:
                logger.error(f'[user_profile] signup error: {error}')
                user.delete()
                return render(request, "unknown_error.html", status=HTTP_SERVICE_UNAVAILABLE)

            return redirect('profile:account_activation_sent')
        else:
            status = HTTP_BAD_REQUEST
    else:
        signup_form = UserForm
        context.update({'signup_form': signup_form})

    return render(request, 'signup.html', context, status=status)


@login_required
@require_http_methods(["GET", "POST"])
def profile_view(request):
    """
    View/Update personal settings
    """
    context = base(request)
    status = HTTP_OK
    if request.method == "POST":
        action = request.POST.get('action', None)
        if action:
            response, status = profile_view_action_processing(request, action)
            return JsonResponse(response, status=status)
        user_update_form, valid = update_user_by_form(request, context)
        # TODO make it more elegant
        # recalculate page size
        context['user'].msg_recalculate_page_size()
        if not valid:
            status = HTTP_BAD_REQUEST
    else:
        user_update_form = UserUpdateForm(initial={'firstname': context['user'].firstname,
                                                   'lastname': context['user'].lastname,
                                                   'patronymic': context['user'].patronymic,
                                                   'birth_date': context['user'].birth_date})
        login(request, context['user'])
    context.update({'update_form': user_update_form, 'user_page_url': context['user'].get_page_url()})
    return render(request, 'profile.html', context, status=status)


def profile_view_action_processing(request, action):
    status = HTTP_OK
    user = request.user
    if action == 'remove_avatar':
        avatar_size = user.avatar_size
        user.remove_avatar()
        if avatar_size:
            # send decrement info
            user.msg_upd_page_size(-avatar_size)
            response = {'result': True, 'default_avatar_url': DEFAULT_AVATAR_URL}
    else:
        response = {'result': False, 'error': 'unknown action'}
        status = HTTP_BAD_REQUEST
    return response, status


@login_required
@require_GET
def logout_view(request):
    logout(request)
    return redirect('posts:mainpage')


def signup_confirm(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('posts:mainpage')
    else:
        return render(request, 'profile_confirmed.html', context={'confirmed': False})


def signup_confirm_sent(request):
    return render(request, 'profile_activation_code_was_sent.html', context={'error': False})

Net640/apps/user_profile/templates/login.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel='stylesheet' href='{% static 'css/base.css' %}' />
    <link rel='stylesheet' href='{% static 'vendor/css/bootstrap/bootstrap.min.css' %}' />
    <title>Login</title>
  </head>
  <body class="body">
    <div class="container">
      <div class="row mt-5">
        <div class="col-12 col-md-6 mx-auto">
            <form method = 'post'>
              {% csrf_token %}
                <fieldset class="form-group">
                  <input type = "text" placeholder = "Username" name = "username" class="form-control">
                  <br>
                  <input type = "password" placeholder = "Password" name = "password" class="form-control">
                  <br>
                </fieldset>

                <input type ="submit" class = "btn btn-secondary w-100" value = "Login">
            </form>
               <div id="pre_submit"></div>

                {% if login_failed %}
                    <div class="row justify-content-center">
                        <div class="failed_animation">
                            <p>Email or password is incorrect. Please try again.</p>
                        </div>
                    </div>
                {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-6 mt-3 pl-5 mx-auto">
          <a class = "row" href={% url 'profile:signup' %}>I am new user</a>
          <a class = "row mt-2" href={% url 'profile:reset_password' %}>Forgot password</a>
        </div>
      </div>
    </div>
  </body>
</html>

Net640/apps/user_profile/templates/password_reset.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel='stylesheet' href='{% static 'vendor/css/bootstrap/bootstrap.min.css' %}' />
    <title>Reset password</title>
  </head>
  <body class="body">
    <div class="container">
      <div class="row mt-5">
        <div class="col-12 col-md-6 mx-auto">

            {% if error or info %}
              <div>
              {{info}}
              {{error}}
              </div>

            {% else %}
              <form method = 'post' enctype="multipart/form-data">
                {% csrf_token %}
                  <fieldset class="form-group">
                    {{password_update_form}}
                  </fieldset>
                  <input type="submit" class="btn btn-secondary w-100" value="Update password">
              </form>
            {% endif %}

        </div>
      </div>
    </div>

  </body>

<script type="text/javascript" src='{% static "user_profile/js/zxcvbn.js" %}'></script>
<script type="text/javascript" src='{% static "user_profile/js/check_password.js" %}'></script>
</html>

Net640/apps/user_profile/templates/password_reset_complete.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel='stylesheet' href='{% static 'vendor/css/bootstrap/bootstrap.min.css' %}' />
    <title>Reset password</title>
  </head>
  <body class="body">
    <div class="container">
      <div class="row mt-5">
        <div class="col-12 col-md-8 mx-auto text-center">
            <p>Your password has been set.  You may go ahead and log in now.</p>
          <a href={% url 'profile:login' %} class="btn btn-secondary w-25">Log in</a>
        </div>
      </div>
    </div>

  </body>

</html>

Net640/apps/user_profile/templates/password_reset_confirm.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel='stylesheet' href='{% static 'vendor/css/bootstrap/bootstrap.min.css' %}' />
    <title>Confirm password</title>
  </head>
  <body class="body">
    <div class="container">
      <div class="row mt-5">
        <div class="col-12 col-md-6 mx-auto">

            {% if validlink %}
              <form method = 'post' enctype="multipart/form-data">
                {% csrf_token %}
                  <fieldset class="form-group">
                    {{form}}
                  </fieldset>
                  <div id="pre_submit"></div>
                  <div class = "btn btn-secondary w-100" id="submit_button">Confirm password</div>
              </form>
            {% else %}
                <p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>
            {% endif %}

        </div>
      </div>
    </div>

  </body>

<script type="text/javascript" src='{% static "user_profile/js/zxcvbn.js" %}'></script>
<script type="text/javascript" src='{% static "user_profile/js/check_password.js" %}'></script>
</html>

Net640/apps/user_profile/templates/password_reset_done.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel='stylesheet' href='{% static 'vendor/css/bootstrap/bootstrap.min.css' %}' />
    <title>Reset password</title>
  </head>
  <body class="body">
    <div class="container">
      <div class="row mt-5">
        <div class="col-12 col-md-6 mx-auto">
            <p>We've emailed you instructions for setting your password if an account exists with the email you entered. You should receive them shortly.</p>
            <p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
            <!-- code for displaying success or error message in template -->
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
                {% endif %}
            </ul>
        </div>
      </div>
    </div>

  </body>

</html>

Net640/apps/user_profile/templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
https://{{ domain }}{% url 'profile:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

Net640/apps/user_profile/templates/password_reset_request.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel='stylesheet' href='{% static 'vendor/css/bootstrap/bootstrap.min.css' %}' />
    <title>Reset password</title>
  </head>
  <body class="body">
    <div class="container">
      <div class="row mt-5">
        <div class="col-12 col-md-6 mx-auto">
            <form method="post">{% csrf_token %}
            <fieldset class="form-group">
                {{form.as_p}}
                <input type="submit" class="btn btn-secondary w-100" value="Reset password">
            </fieldset>
            </form>
        </div>
      </div>
    </div>

  </body>

</html>

Net640/apps/user_profile/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block css_rules %}
<link rel='stylesheet' href="{% static 'vendor/css/fontawesome/all.css' %}" />
{% endblock %}

{% block title %}Update personal data{% endblock %}

{% block content %}
<div class="container">
  <!-- default values -->
  <div data-application-variables="default_values" class="d-none"
       data-user_page_url={{user_page_url}}
       >
  </div>
  <!-- end of default values -->

  <div class="row mt-2 no_link_behaviour">
    <a class="col-8 col-md-2 offset-md-10 menu__item" id="copy_link" data-user-id={{user.id}}>Copy link to my page</a>
  </div>

  <div class="row mt-3">
    <div class="col-12 col-md-6 mx-auto">
      <form method='post' id="update_personal_data__form" enctype="multipart/form-data">
        <fieldset class="form-group">
          {% csrf_token %}
          {{update_form}}
        </fieldset>
        <div class="row mt-2 mb-2 text-center">
          {% if user.avatar %}
            <div class="col-10 offset-1">
              <img src="{{user.get_avatar_url}}" id="preview_image" data-id-input-image="id_avatar" class="w-50 mx-auto"/>
            </div>
            <div class="col-1 my-top mx-auto">
              <i class="far fa-trash-alt"></i>
            </div>
          {% else %}
            <div class="col-10 mx-auto">
              <img src="{{user.get_avatar_url}}" id="preview_image" data-id-input-image="id_avatar" class="w-50 mx-auto"/>
            </div>
          {% endif %}
        </div>
        <input type="submit" class="btn btn-primary w-100" id="submit_button" value="Update"></input>
      </form>
      <div id="pre_submit"></div>
    </div>
  </div>

</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript" src='{% static "js/basic_func.js" %}'></script>
<script type="text/javascript" src='{% static 'js/preview_image.js' %}'></script>
<script type="text/javascript" src='{% static "user_profile/js/check_password.js" %}'></script>
<script type="text/javascript" src='{% static "user_profile/js/profile.js" %}'></script>
{% endblock %}

Net640/apps/user_profile/templates/profile_activation_code_was_sent.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel='stylesheet' href='{% static 'vendor/css/bootstrap/bootstrap.min.css' %}' />
    <title>Confirmation</title>
  </head>
  <body class="body">
    <div class="container">
      <div class="row mt-5">
        <div class="col-12 col-md-6 mx-auto">
          {% if not error %}
          A confirmation code link has been sent to your email address. 
          {% else %}
          {{error}}
          {% endif %}
        </div>
      </div>
    </div>

  </body>

</html>

Net640/apps/user_profile/templates/profile_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

https://{{ domain }}{% url 'profile:signup_confirm' uidb64=uid token=token %}
{% endautoescape %}

Net640/apps/user_profile/templates/profile_confirmed.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel='stylesheet' href='{% static 'vendor/css/bootstrap/bootstrap.min.css' %}' />
    <title>Confirmation</title>
  </head>
  <body class="body">
    <div class="container">
      {% if confirmed %}
        <div class="row mt-3">
          <div class="col-12 col-md-8 text-center mx-auto">
            <p>Your profile is confirmed!</p>
          </div>
        </div>

        <div class="row mt-3 no_link_behaviour">
          <div class="col-12 col-md-8 mx-auto text-center">
            <a href="{% url 'login' %}" class="btn btn-secondary w-25">Login</a>
          </div>
        </div>
      {% else %}
        <div class="row mt-5 col-12 col-md-8 mx-auto">
          <p>There are errors during confirming your profile</p>
        </div>
      {% endif %}
    </div>

  </body>

</html>

Net640/apps/user_profile/templates/signup.html
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel='stylesheet' href='{% static 'vendor/css/bootstrap/bootstrap.min.css' %}' />
    <title>Signup</title>
  </head>
  <body class="body">
    <div class="container">
      <div class="row mt-5">
        <div class="col-12 col-md-6 mx-auto">
            <form method = 'post' enctype="multipart/form-data">
              {% csrf_token %}
                <fieldset class="form-group">
                  {{signup_form}}
                </fieldset>
            </form>
               <div id="pre_submit"></div>
                <div class="row mt-2 mb-2">
                  <img src="" id="preview_image" data-id-input-image="id_avatar" class="w-50 mx-auto d-none"/>
                </div>
               <div class = "btn btn-secondary w-100" id="submit_button">Signup</div>

        </div>
      </div>
    </div>

  </body>

<script type="text/javascript" src='{% static "user_profile/js/zxcvbn.js" %}'></script>
<script type="text/javascript" src='{% static "user_profile/js/check_password.js" %}'></script>
<script type="text/javascript" src='{% static "js/preview_image.js" %}'></script>
</html>