Net640/apps/images/urls.py
from django.urls import path, re_path
from Net640.apps.images import views

app_name = 'images'
urlpatterns = [
    path(r'my_images/', views.user_images_view, name="my_images"),
    # TODO move to rest api
    path(r'action/', views.user_image_action, name="user_image_action"),
]

Net640/apps/user_posts/urls.py
from django.urls import path, re_path
from Net640.apps.user_posts import views

app_name = 'posts'
urlpatterns = [
    path(r'', views.mainpage_view, name="mainpage"),
    # TODO move to rest api
    re_path(r'post/(?P<user_id>[\d]*)?', views.user_post_processing, name="user_post_processing"),
    re_path(r'comment/(?P<post_id>[\d]*)?', views.user_comment_processing, name="user_comment_processing"),
    path(r'news/', views.user_news, name="news"),
]

Net640/apps/user_profile/urls.py
from django.urls import path, re_path
from Net640.apps.user_profile import views, classy_views

app_name = 'profile'
urlpatterns = [
    path(r'signup/', views.signup_view, name="signup"),
    path(r'login/', views.login_view, name="login"),
    path(r'my_profile/', views.profile_view, name="my_profile"),
    path(r'logout/', views.logout_view, name="logout"),
    path(r'account_activation_sent/', views.signup_confirm_sent, name='account_activation_sent'),
    re_path(r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.signup_confirm, name='signup_confirm'),
    path(r'reset_password/', classy_views.Net640PasswordResetView.as_view(), name="reset_password"),
    path(r'reset/done/', classy_views.Net640PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(r'reset/complete/', classy_views.Net640PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    re_path(r'reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            classy_views.Net640PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

Net640/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from Net640.settings import MEDIA_ROOT, MEDIA_URL, STATIC_URL, STATIC_ROOT
from django.conf.urls.static import static

import Net640.apps.images.views as image_views

try:
    from Net640.local_settings import DEBUG
except ImportError:
    from Net640.settings import DEBUG

media_url = [
    # next function is working in cooperation with nginx:
    #  - nginx recieve request for some resource in /media/*
    #  - ngnix moves this request to views.get_image
    #  - get_image checks permissions and return resource or return 404
    re_path(r'^media/users/(?P<username>(\w*))/(?P<imagename>(.*))', image_views.get_image, name="get_image"),
]


# for sentry debug
def trigger_error(request):
    1 / 0


urlpatterns = [
    path('', include('Net640.apps.user_posts.urls', namespace='posts')),
    path('user/', include('Net640.apps.user_profile.urls', namespace='profile')),
    path('friends/', include('Net640.apps.friends.urls', namespace='friends')),
    path('chat/', include('Net640.apps.chat.urls', namespace='chat')),
    path('images/', include('Net640.apps.images.urls', namespace='images')),
    path('admin/', admin.site.urls),
    path('sentry-debug/', trigger_error),
] + media_url

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

Net640/apps/user_posts/models.py
import os
import logging

from django.db import models
from django.conf import settings
from django.utils import timezone

from Net640.apps.images.models import user_directory_path
from Net640.mixin import LikesMixin
from Net640.apps.user_posts.mixin import AsDictMessageMixin
from Net640.apps.user_posts.exceptions import PostException


class Post(LikesMixin, AsDictMessageMixin, models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(default=timezone.now, blank=True)
    image = models.ImageField(upload_to=user_directory_path)
    image_size = models.IntegerField(default=0)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, default=None, related_name="post_likes")

    class Meta:
        ordering = ["-date"]
        app_label = 'user_posts'

    def get_image_url(self):
        if self.image:
            return self.image.url

    def get_size(self):
        """ calculate post size """
        # TODO Currently, this method calculates the size approximately. Need to calculate likes.
        try:
            post_size = 0
            post_size += len(str(self.id))
            post_size += len(str(self.user.id))
            post_size += len(self.content)
            post_size += len(str(self.user_id))
            post_size += len(str(self.date))
            if self.image:
                post_size += self.image.size
        except Exception as error:
            raise PostException("Got error when calculating post size {}".format(error))
        return post_size

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            post_size = self.get_size()
            if post_size:
                # send increment info
                self.user.msg_upd_page_size(post_size)
        except PostException as error:
            logging.error(error)

    def delete(self, *args, **kwargs):
        try:
            post_size = self.get_size()
            if post_size:
                # send decrement info
                self.user.msg_upd_page_size(-post_size)
        except PostException as error:
            logging.error(error)
        finally:
            super().delete(*args, **kwargs)
            if self.image:
                os.remove(self.image.path)

    def as_dict(self, executor):
        result = super().as_dict(executor)
        result.update({'comments': [comment.as_dict(executor) for comment in Comment.objects.filter(post=self)],
                       'image_url': self.get_image_url()})
        return result


class Comment(LikesMixin, AsDictMessageMixin, models.Model):
    """
    Comment model for user post
    """
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, default=None, related_name="comment_likes")

    class Meta:
        ordering = ['-date']
        app_label = 'user_posts'

Net640/apps/user_posts/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext_lazy as _

from Net640.apps.user_posts.models import Post, Comment
from Net640.settings import MAX_PAGE_SIZE


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content', 'image')

    content = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        self.fields['content'].widget.attrs.update({
            'placeholder': 'Your post', 'class': 'form-control w-100 mb-3', 'rows': 3,
        })
        self.fields['content'].help_text = ''
        self.fields['content'].label = ''
        self.fields['content'].required = True

        self.fields['image'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['image'].help_text = ''
        self.fields['image'].label = 'Attach'
        self.fields['image'].required = False
        self.fields['image'].widget.attrs.update({'class': 'd-none'})

    def clean(self):
        cleaned_data = super().clean()
        validation_errors = list()

        # without user we can't calculate page size.
        if not self.user:
            raise forms.ValidationError(_('Anonymous posts are not allowed'))

        # Calculate form size
        # use latest id as reference
        try:
            form_size = len(str(Post.objects.latest('id').id))
        except ObjectDoesNotExist:
            form_size = 1
        form_size += len(str(cleaned_data['content'])) + len(str(self.instance.date)) + len(str(self.user.id))
        if cleaned_data['image']:
            form_size += cleaned_data['image'].size

        if self.user.get_size() + form_size > MAX_PAGE_SIZE:
            validation_errors.append(forms.ValidationError(_('Not enough space!'), code='oversize'))
        if validation_errors:
            raise forms.ValidationError(validation_errors)

        return cleaned_data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

    content = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        self.fields['content'].widget.attrs.update({
            'placeholder': 'Your comment', 'class': 'form-control w-100 mb-3', 'rows': 1,
        })
        self.fields['content'].help_text = ''
        self.fields['content'].label = ''
        self.fields['content'].required = True

Net640/apps/user_posts/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, reverse
from django.views.decorators.http import require_http_methods

from Net640.apps.user_posts.models import Comment
from Net640.apps.user_posts.forms import PostForm, CommentForm
from Net640.apps.user_posts.helpers import user_comment_process_action_post, user_post_process_action_post
from Net640.apps.user_posts.helpers import user_news_processing_post_action
from Net640.apps.user_profile.helpers import base


@require_http_methods(["GET", "POST"])
def mainpage_view(request):
    context = base(request)
    context['explicit_processing_url'] = None

    if context['user']:
        post_form = PostForm()
        if request.method == "POST":
            new_post_form = PostForm(request.POST, request.FILES, user=request.user)
            if new_post_form.is_valid():
                try:
                    new_post = new_post_form.save(commit=False)
                    new_post.user = request.user
                    if new_post.image:
                        new_post.image_size = new_post.image.size
                    new_post.save()
                except Exception:
                    pass
            else:
                # show form errors to user
                post_form = new_post_form
        context.update({'comment_form': CommentForm()})
        context.update({'posts': [], 'post_form': post_form})
        return render(request, 'main_page.html', context)
    else:
        return render(request, 'info.html')


@require_http_methods(["GET", "POST"])
def user_post_processing(request, user_id=None):
    """
    Function for processing all actions on user posts
    """
    result = dict()
    if request.method == "POST":
        # possible actions are: like, dislike, remove the post
        result = user_post_process_action_post(request, user_id)
    # TODO There will be method for processing creation of new post

    return JsonResponse(result)


@login_required
@require_http_methods(["GET", "POST"])
def user_news(request):
    context = {'explicit_processing_url': reverse('posts:news')}

    if request.method == "POST":
        result = user_news_processing_post_action(request)
        return JsonResponse(result)

    return render(request, 'news.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def user_comment_processing(request, post_id=None):
    """
    Function for processing all actions on user comments
    """
    if request.method == "POST":
        # possible actions are: like, dislike, remove the comment, add a new comment
        result = user_comment_process_action_post(request)
    else:
        # get request returns the list of comments
        result = {'comments': [obj.as_dict(request.user) for obj in Comment.objects.filter(post_id=post_id)]}

    return JsonResponse(result)

Net640/apps/user_posts/templates/add_comment_modal.html
<div id="modal_add_comment" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Write a comment</h5>
        <button type="button" class="close" v-on:click="close_modal_add_comment">
          <i class="fas fa-times"></i>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ comment_form }}
          <input type="submit" class="btn btn-secondary w-100" v-on:click="add_comment" value="Add comment"> 
        </form>
      </div>
    </div>
  </div>
</div>

Net640/apps/user_posts/templates/main_page.html
{% extends "base.html" %}

{% block title %}My page{% endblock %}
{% load static %}
{% block css_rules %}
<link rel='stylesheet' href='{% static 'user_posts/css/user_posts.css' %}' />
<link rel='stylesheet' href="{% static 'vendor/css/fontawesome/all.css' %}" />
{% endblock %}

{% block content %}
{% if user %}
<div class="container">
  <div class="row mt-2 no_link_behaviour">
    <a class="col-8 col-md-2 mr-2 menu__item" href={% url 'images:my_images' %}>My images</a>
    <a class="col-8 col-md-2 mr-2 menu__item" href={% url 'profile:my_profile' %}>My profile</a>
  </div>

  <div class="row mt-3">
    <div class="col-12 col-md-9 mx-auto">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ post_form }}

        <div class="row mt-2 mb-2">
          <img src="" id="preview_image" data-id-input-image="id_image" class="w-50 mx-auto d-none"/>
        </div>
        <input type="submit" class ="btn btn-secondary w-100" value="Send Post"> 
      </form>
    </div>
  </div>
</div>

{% include 'user_posts.html' %}

{% endif %}
{% endblock %}

{% block scripts %}
<script type="text/javascript" src='{% static "js/basic_func.js" %}'></script>
<script type="text/javascript" src='{% static 'js/preview_image.js' %}'></script>
{% endblock %}

Net640/apps/user_posts/templates/news.html
{% extends "base.html" %}

{% block title %}News{% endblock %}
{% load static %}
{% block css_rules %}
<link rel='stylesheet' href="{% static 'vendor/css/fontawesome/all.css' %}" />
{% endblock %}

{% block content %}
<div class="container">
  <div class="row mt-2 no_link_behaviour">
    <a class="col-8 col-md-2 mr-2 menu__item" href={% url 'images:my_images' %}>My images</a>
    <a class="col-8 col-md-2 menu__item" href={% url 'profile:my_profile' %}>My profile</a>
  </div>
</div>

{% include 'user_posts.html' %}

<form method="post" class="d-none">
    {% csrf_token %}
</form>

{% endblock %}

{% block scripts %}
<script type="text/javascript" src='{% static "vendor/js/vue.js" %}'></script>
<script type="text/javascript" src='{% static "js/basic_func.js" %}'></script>


{% endblock %}

Net640/apps/user_posts/templates/user_posts.html
<div id="vue_postscomments_app" class="">
  <!-- default values -->
  <div data-application-variables="default_values" class="d-none"
      {#In some cases, for example, a user visits a news page, we want to change the post processing url.#}
      {#It's easier than creating a new js module to process the same data.#}
      {% if explicit_processing_url %}
       data-userpost-processing-url={{explicit_processing_url}}
      {% else %}
       data-userpost-processing-url="{% url 'posts:user_post_processing' %}"
      {% endif %}
       data-usercomment-processing-url="{% url 'posts:user_comment_processing' %}"
       >
  </div>
  <!-- end of default values -->

  <div v-if="posts" class="container mt-5">
        <div v-for="post in posts" class="row posts_list__item w-90 mx-auto" data-message-type='post'>
          <div class="col-12 col-md-9 mx-auto">
            <div v-if="post.image_url" class="row mt-1">
                <img v-bind:src="post.image_url" class="col-12 mx-auto"/>
            </div>
            <div class="row">
              <div class="col-10">
                <div class="wordwrap">
                  [[post.content]]
                </div>
              </div>
              <div class="col-2 text-right">
                <a v-bind:href=post.author_page>
                  <img v-bind:src="post.author_thumbnail_url"/>
                </a>
                <div class="posts_list__item_author_and_date">
                  [[post.author]] [[post.date]]
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-1 text-center align-self-right">
                <div class="badge badge-dark">[[post.rating.toFixed(1)]]</div>
              </div>
              <div class="col-1">
                <i v-if="post.user_has_like" class="fas fa-heart" v-on:click="action_on_user_message" data-action='dislike' v-bind:data-action-url=post_processing_url v-bind:data-message-id=post.id></i>
                <i v-else class="far fa-heart" v-on:click="action_on_user_message" data-action='like' v-bind:data-action-url="post_processing_url" v-bind:data-message-id="post.id"></i>
              </div>
              <div v-if="post.is_owner" class="col-1 offset-9 text-right align-self-right">
                <i class="far fa-trash-alt" v-on:click="action_on_user_message" data-action='remove' v-bind:data-action-url=post_processing_url v-bind:data-message-id=post.id></i>
              </div>
            </div>
            
            <div class="row mt-4">
              <div class="col-12 col-md-12 mx-auto">
                <div class="btn btn-secondary p-1" v-bind:data-message-id=post.id v-on:click="show_modal_add_comment"><div class="small">add comment</div></div>
              </div>
            </div>

            <div v-if="post.comments" class="container mt-5">
            <!--<div v-for="comment in post.comments" v-bind:key="comment.id" data-message-type='comment' class="row posts_list__item w-90 mx-auto">-->
            <div v-for="comment in post.comments" v-bind:key="comment.id" data-message-type='comment' class="row w-90 mx-auto">
            <div class="col-12 col-md-9 mx-auto">
            <hr/>
              <div class="row">
                <div class="col-10">
                  <div class="wordwrap">
                    [[comment.content]]
                  </div>
                </div>
                <div class="col-2 text-right">
                  <a v-bind:href=comment.author_page>
                    <img v-bind:src="comment.author_thumbnail_url"/>
                  </a>
                  <div class="posts_list__item_author_and_date">
                    [[comment.author]] [[comment.date]]
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-1 text-center align-self-right">
                  <div class="badge badge-dark">[[comment.rating.toFixed(1)]]</div>
                </div>
                <div class="col-1">
                  <i v-if="comment.user_has_like" class="fas fa-heart" v-on:click="action_on_user_message" data-action='dislike' v-bind:data-action-url=comment_processing_url v-bind:data-message-id=comment.id></i>
                  <i v-else class="far fa-heart" v-on:click="action_on_user_message" data-action='like' v-bind:data-action-url="comment_processing_url" v-bind:data-message-id="comment.id"></i>
                </div>
                <div v-if="comment.is_owner" class="col-1 offset-9 text-right align-self-right">
                  <i class="far fa-trash-alt" v-on:click="action_on_user_message" data-action='remove' v-bind:data-action-url=comment_processing_url v-bind:data-message-id=comment.id></i>
                </div>
              </div>
            </div>
            </div>
            </div>

          </div>
        </div>
  </div>


{% include 'add_comment_modal.html' %}
</div>

{% load static %}
<script type="text/javascript" src='{% static 'user_posts/js/user_posts_and_comments.js' %}'></script>