Net640/apps/images/urls.py
from django.urls import path, re_path
from Net640.apps.images import views

app_name = 'images'
urlpatterns = [
    path(r'my_images/', views.user_images_view, name="my_images"),
    # TODO move to rest api
    path(r'action/', views.user_image_action, name="user_image_action"),
]

Net640/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from Net640.settings import MEDIA_ROOT, MEDIA_URL, STATIC_URL, STATIC_ROOT
from django.conf.urls.static import static

import Net640.apps.images.views as image_views

try:
    from Net640.local_settings import DEBUG
except ImportError:
    from Net640.settings import DEBUG

media_url = [
    # next function is working in cooperation with nginx:
    #  - nginx recieve request for some resource in /media/*
    #  - ngnix moves this request to views.get_image
    #  - get_image checks permissions and return resource or return 404
    re_path(r'^media/users/(?P<username>(\w*))/(?P<imagename>(.*))', image_views.get_image, name="get_image"),
]


# for sentry debug
def trigger_error(request):
    1 / 0


urlpatterns = [
    path('', include('Net640.apps.user_posts.urls', namespace='posts')),
    path('user/', include('Net640.apps.user_profile.urls', namespace='profile')),
    path('friends/', include('Net640.apps.friends.urls', namespace='friends')),
    path('chat/', include('Net640.apps.chat.urls', namespace='chat')),
    path('images/', include('Net640.apps.images.urls', namespace='images')),
    path('admin/', admin.site.urls),
    path('sentry-debug/', trigger_error),
] + media_url

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

Net640/apps/images/models.py
import uuid

from django.db import models
from django.conf import settings

from Net640.mixin import LikesMixin


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/users/<username>/<uuid4>.<ext>
    ext = filename.split('.')[-1]
    return 'users/{0}/{1}.{2}'.format(instance.user.username, uuid.uuid4(), ext)


def user_avatar_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/users/<username>/avatar/avatar.<ext>
    return 'users/{0}/avatar/avatar.{1}'.format(instance.username, filename.split('.')[-1])


class Image(LikesMixin, models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, blank=True)
    image = models.ImageField(upload_to=user_directory_path)
    image_size = models.IntegerField(default=0)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, default=None, related_name="message_likes")

    class Meta:
        app_label = 'images'

    def delete(self, *args, **kwargs):
        author_id = str(self.user.id)
        image_size = len(str(self.id))
        image_size += len(self.description)
        image_size += self.image.size
        image_size += len(str(self.uploaded_at))
        image_size += len(author_id)

        super().delete(*args, **kwargs)
        if image_size:
            # send decrement info
            self.user.msg_upd_page_size(-image_size)

Net640/apps/images/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext_lazy as _

from Net640.apps.images.models import Image
from Net640.settings import MAX_PAGE_SIZE


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('description', 'image')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        self.fields['description'].widget.attrs.update({
            'placeholder': 'Image description', 'class': 'form-control mb-3'
        })
        self.fields['description'].help_text = ''
        self.fields['description'].label = ''
        self.fields['description'].required = True

        self.fields['image'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['image'].help_text = ''
        self.fields['image'].label = ''
        self.fields['image'].required = True

    def clean(self):
        cleaned_data = super().clean()
        validation_errors = list()

        # without user we can't calculate page size.
        if not self.user:
            raise forms.ValidationError(_('Anonymous posts are not allowed'))

        # Calculate form size
        # use latest id as reference
        try:
            form_size = len(str(Image.objects.latest('id').id))
        except ObjectDoesNotExist:
            form_size = 1

        form_size += len(cleaned_data['description']) + cleaned_data['image'].size
        if self.user.get_size() + form_size > MAX_PAGE_SIZE:
            validation_errors.append(forms.ValidationError(_('Not enough space!'), code='oversize'))
        if validation_errors:
            raise forms.ValidationError(validation_errors)

        return cleaned_data

Net640/apps/images/views.py
import os
import logging
import mimetypes

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_GET

from Net640.apps.images.forms import ImageForm
from Net640.apps.images.models import Image
from Net640.apps.user_profile.models import RELATIONSHIP_FRIENDS
from Net640.errors import NotEnoughSpace
from Net640.settings import MEDIA_ROOT


User = get_user_model()
logger = logging.getLogger(__name__)
users_media = os.path.join(MEDIA_ROOT, 'users')


@login_required
@require_http_methods(["GET", "POST"])
def user_images_view(request):
    """
    This view gives us a page with images album of logged user.
    In POST method this view will add new image.
    """
    master = request.user

    images = []
    for image in Image.objects.filter(user=master):
        images.append({'url': image.image.url,
                       'description': image.description,
                       'id': image.id,
                       'user_has_like': image.has_like(master),
                       'rating': image.get_rating(),
                       'width': image.image.width})

    if request.method == 'POST':
        image_form = ImageForm(request.POST, request.FILES, user=request.user)
        if image_form.is_valid():
            try:
                image = image_form.save(commit=False)
                image.user = master
                image.save()
            except NotEnoughSpace:
                pass
            return redirect('images:my_images')
    else:
        image_form = ImageForm()
    return render(request, 'user_images.html', {
        'image_form': image_form,
        'username': master.username,
        'images': images
    })


@login_required
@require_POST
def user_image_action(request):
    context = {}
    user = request.user
    image_id = request.POST.get('image_id', None)
    image = get_object_or_404(Image, id=image_id)
    action = request.POST.get('action', None)

    if action == 'like':
        image.add_like(user)
        context.update({"result": True, "likes": image.get_rating()})
    if action == 'dislike':
        image.remove_like(user)
        context.update({"result": True, "likes": image.get_rating()})
    if action == 'remove':
        if user == image.user:
            image.delete()
            context.update({"result": True})
    return JsonResponse(context)


@require_GET
def get_image(request, username, imagename):
    """
    This function are working in cooperation with Nginx.
    Function is checking permission on requested resource before giving it to user.
    """
    master = request.user
    user = get_object_or_404(User, username=username)
    if master == user or master.check_relationship(user) == RELATIONSHIP_FRIENDS:
        file_on_disk = os.path.join(users_media, username, imagename)
        file_size = os.path.getsize(file_on_disk)
        content_type, _ = mimetypes.guess_type(imagename)
        response = HttpResponse()
        response.status_code = 200
        response['X-Accel-Redirect'] = request.path
        response['Content'] = content_type
        response['Content-length'] = file_size
    else:
        response = HttpResponseNotFound("File not found:{}".format(imagename))
    return response

Net640/apps/images/templates/user_images.html
{% extends "base.html" %}

{% block title %}My images{% endblock %}
{% load static %}
{% block css_rules %}
<link rel='stylesheet' href="{% static 'vendor/css/fontawesome/all.css' %}" />
<link rel='stylesheet' href="{% static 'images/css/upload_image.css' %}" />
{% endblock %}

{% block content %}

<div class="container">
  <div class="row mt-3">
    <div class="col-12 col-md-6 mx-auto">
      <form class="mx-auto" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group text-center">
          {{ image_form.as_p}} 
        </fieldset>
          <label for="id_image" class="btn btn-secondary w-100 mx-auto">Select image</label>
          <div class="row mt-2 mb-2">
            <img src="" id="preview_image" data-id-input-image="id_image" class="w-50 mx-auto"/>
          </div>
          <button class="btn btn-secondary w-100 mx-auto" type="submit">Upload</button> 
      </form>
    </div>
  </div>
</div>

<div class="container">
    {% if images|length > 0 %}
      {% for image in images %}
        <div class="row mt-3 text-center">
          <img src="{{image.url}}" alt="{{image.description}}" class="col-10 mx-auto">
          <div class="col-1"><i class="far fa-trash-alt" data-action='remove' data-action-url="{% url 'images:user_image_action' %}" data-image-id="{{ image.id }}"></i></div>
          <div class="col-1">
            <div class="badge badge-dark">{{ image.rating | floatformat:1}}</div>
            {% if image.user_has_like %}
            <i class="fas fa-heart" data-action='dislike' data-action-url="{% url 'images:user_image_action' %}" data-image-id="{{ image.id }}"></i>
            {% else %}
            <i class="far fa-heart" data-action='like' data-action-url="{% url 'images:user_image_action' %}" data-image-id="{{ image.id }}"></i>
            {% endif %}
          </div>
        </div>
      {% endfor %}
    {% else %}
    {% endif %}

</div>

{% endblock %}

{% block scripts %}
{% load static %}
<script type="text/javascript" src='{% static 'js/basic_func.js' %}'></script>
<script type="text/javascript" src='{% static 'images/js/user_image_actions.js' %}'></script>
<script type="text/javascript" src='{% static 'js/preview_image.js' %}'></script>
{% endblock %}